language: r
cache: packages
r_packages:
- covr
- drat
- pkgdown
- lintr
before_install:
- bash make.sh
after_success:
- Rscript -e 'lintr::lint_package()'
- Rscript -e 'library(covr); codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript
  -e 'Sys.sleep(30);install.packages("fhi",repos="https://folkehelseinstituttet.github.io/drat/");pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
  - secure: urwj42/kyHSCIwJHPGUapckqZ2k0d2w+HFwJLvYfdHPHGOPWpuVdc+X7R/DgrBhTCZq2CIYKrVVKdTwHLBcq7l0wyXXJ8EkUQEK37FDHQlXoBPbarKf1FrDzG/dHqaSbjIoxe15+B0O9kd+5sAEZM9rUfxPU4asEZLqQPacHmRfMY87F3c3Lm/gNPIJgpGt3fxiunVJq7MPso3JufWgv7RmMV61bUs1ZGl/7SDDIVpk8K5BhMZiq1zQ3C8R9y9r0XkYC4P4IsTralB89g6eyRuVtFAAJij8aGN5pgAH7V3v1n4IKPnyqSfzwe9LPoJYKlvoGfmV0jM6cfhDWGOMuElFt/Y64M1e6IG9tfW5NvQJOTMtLe7X/SQkIqtwD9t/aBy9bBSbjktNt8XN4/saLOYoW+9b5UV/gs3kRojazNZ2ipkH1dOYAhqhSgG1KYKCWUAdCK1YZe8nbTdMf68k0SS9wumtybnuISB3Mo31nxUEHEHHNr215KwtAehJvGZ0oLeP1h1l8g0uuxi9MpIMJlvXpkoOQwSPVCWce6vmhhUjs44tr4F/cJxE/El40RMJ9EQyqQ6fPFEp44CfS1Owd5bPBvDb8vP1xyvrmK6S0GBPnj7VMNrjRtRC9XHSqpSY3FUdyrWW4hzsRCkvxwP3tIAXTBmUBQrYx+tGVE5zmWGQ=
  - secure: FhAObhvqd+d8GUW06RgxgOBsuJBWrgxyDRifml5VZ7hRAYDSJolRiYtWwcqD4HJ3LrrrUSOvEW1XwLOExQZxlZ4Cz+w3YCaLNf4J2YJ5fYDZvEyMzz+VzVvv8RyXxZ5IMa2WDtevzaJXxJpBDj6TyE7mxevCW1U9H99+KQkgYH2rwc+iSt6bkcJxNKP52eiAn2c4PKD6QxBep4LaSQO/0v0wbuGwKOqln0Ol0pZJmZpDndrkWKrses6Qj92lRajqEOcTv7ux0CYNOXiCE1uMhW+2Q/ULBQ9BKHGyCymIkj8/HMp/GjN9hepxf34lbF5sDRju6Gpl01R9VdbYXvWEfKVytjrmjubRUBeLD5AoQpRXZe+YiUB06s+IjN4ar2Ym6VbLlwn8q5M/Mi1gzszYkarCmqALC4ChAjTUXU1IIuFbqOxdxh2A4AosXlGjZT9OAu61WIBQMXT+oLM9JoQp4C9hYV6cudmnT5JKSV2YoZXk7tXzOVQwIYcqWsxJuyIxjVwbPD1Q6kIXDYdxGKAQtzaP2v8XUjbnj+IhKw1OfCnlYj7bz+F2Mfaq6iPWSi0UAWdRfYYc32DYSxp6+NRyPyWUGuqwJ0nvXfIQNQrGBy7gI0Th1H9D79G3J1HKIsS9iIMdzjuh/yeKm3lespoqvJyMNzuBTXZvUIQr2vGydhY=
