language: r
cache: packages
r_packages:
- covr
- drat
- pkgdown
before_install:
- bash make.sh
after_success:
- Rscript -e 'library(covr); codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript
  -e 'Sys.sleep(10);install.packages("sykdomspuls",repos="https://folkehelseinstituttet.github.io/drat/");pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
  - secure: rRWS3BaLxm5OeAUt2Q/HnKzW/+680vN77Hu8YGYJXBlDrKtYyYjXmkAqCsMu3dA41qOBYQvdmkOy/D/5TEhIIc0D18ohsoqqxAxGtpGnIDkw54GXyyoZ3fdTCrh/MPqMMt/n/3oCQ5TTRToz/VwXfGOBfVBWYeIEYiTW3WWhdUPd1KDZGSBNudutTddBb9Hss6/FSomD/1bVeImnSmEjiY8do/tW1xFPR/N8o0a0aA1Q5vtQLy2EdX1EYeg1JMNxInNIdOjuHgvfYii+uctOym5n7L5Phf58YsBQ1ymYiRyIE9GJXJenz025N6ZN+m86h/97LQ8JChkFLq8G883Y718eiKOJ0pou301l71B/cw3e7H5or6GQGa3YihT1/3+b4Oe978FhmTNo4HZkpBbmlnUldRPYBiz7MR1rYGZSZS2US/MBWfLIJlhpIKgbatQuFNoOanyTa1gmy8CYeR0FEIAUlhjSP+EPrSzCIbargNBLc/A4mhCdhQmobt+cfHQH3a0DbBk3gVrW/fX3obu84JVcrQGzBEvuz2s8IJI5n3W0s5X97QecCG5ql3beug8sVmUP4Qcxqz/BnebopWo1erj72zq8UcsVmdwmPH433hOQ83JGJMWtY0ePjlnhwaqe9SXLOzstff/kp/8eDY5DZCiIIVf2ljq6lSux7H+hryk=
  - secure: Otu5EB8T2/UqA8wFOdbKVp/EsKMcArrUYDxHiANwrAPvNxDWxCIt5fMf2LI4XuItZSFD/l/z/jEKz1HgrQUekKawBgXaqQabVXLryX7trTuQoGgk0naAsa6g9M13WN4QqV1o2Xs4piK0+mtQ1SYLbMH8ClulsiakUmIwZIQI+aReR1zQT1lRXcBCyypyn2ntDfpv6IuEX2fjkP0uA/auoSDyEnKCuEBp0vdcx76tBWSiPHkPsdbKSkgCAhYorPTpSgFotXc3uNdmGiJ77LuXq/IS6y0DjiylYmeW3hcPHT8b0jfRAMyu6bvnXAiOkR8ltAyL4pqUiLp99YJdFS9f/hfYYzldM7Uh47ekR7lCbm2c3FT4YRZp3OpOWWERebEG67OJV/rZ6zoQwJ//WG2HlVTbWKRCu3MU/moIhZJxNr88mH8nnp+YHIrkvHfVYWXgX/va1Y+onCuAg3SsbzIy6fG2Fwo9iqx7ZXAtiTRUrlZIlJ8/yX6kUkJWqvRH3jIyS15kDuWmZ16NqTIwhLj0E+BRyjcQa9xrrdfw5UANk/sCjG4gAeRqGO2BjTOHIvkcpSiecui2GQHFkwbZtTpCvt5hzS/Cr4AQnP4XuSHqRgBTL1hOgybxsvwiCz/vCANAjVpfmbUVoa1sbca+7PIaKugFG2CIr163N3m/G65JksQ=
